# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'shashankbarsin/bootcamp-demo:$(build.buildId)'

steps:
-task: Docker@1
  displayName: Container registery login
  inputs:
  command:login
  azuresubcriptionEndpoint: demo123
  azureContainerRegistry:devcamp123shasb.azurecr.io
-script: docker build -t devcamp123shasb.azure.io/$(imageName) /.app
- script: docker push devcamp123shasb.azure.io/$(imageName) 
script: docker  build -t developer-camp:dev ./app
